eos-stage-flatpak: cope with remote names containing '.'
`flatpak-builder --install`, among other tools, creates remotes of the
form "org.vim.Vim-origin". `ostree config get KEY` splits KEY on the
first '.' it contains, leading to:

    ++ ostree --repo=/var/lib/flatpak/repo config get 'remote "org.vim.Vim-origin".url'
    error: Key file does not have group “remote "org”

Since v2018.8, `ostree config get|set` accept a `--group` parameter,
precisely to deal with this case. Bump the version we depend on, and use
it.

https://phabricator.endlessm.com/T25253