eos-download-image: handle missing manifest gracefully
Without this change, running `eos-download-image --product esodvd` gives
you a long traceback followed by:

    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

With this change, you get a more human-readable error describing the
actual cause:

    Couldn't fetch manifest for product esodvd

    403 Client Error: Forbidden for url: https://d1anzknqnc1kmb.cloudfront.net/releases-esodvd-3.json

Found while QAing https://phabricator.endlessm.com/T18653